"""Initial db migration.

Revision ID: 0947ef779dea
Revises: 
Create Date: 2026-06-25 12:40:34.192289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0947ef779dea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctors')
    op.drop_table('hospitals')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('hospital_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('hospital_address', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('hospitals_pkey'))
    )
    op.create_table('doctors',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=70), autoincrement=False, nullable=False),
    sa.Column('gmail', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('phone_no', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('specialization', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('experience', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qualifications', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('pfp_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('biometric_method', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('verification_code', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('doctor_id', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('pin', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('agreed_pin_warn', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('accepted_terms', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('hospital_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('doctors_hospital_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('doctors_pkey'))
    )
    # ### end Alembic commands ###
