"""Edit report_pdf_url to report_file_name in reports

Revision ID: 37f8c4ebafc8
Revises: ab6266e02e78
Create Date: 2026-07-10 13:34:30.543006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37f8c4ebafc8'
down_revision: Union[str, Sequence[str], None] = 'ab6266e02e78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'report_pdf_url', new_column_name='report_file_name')
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'report_file_name', new_column_name='report_pdf_url')
    # ### end Alembic commands ###
