"""Added gmail, password column in patients table.

Revision ID: 5f7253b8835f
Revises: 0947ef779dea
Create Date: 2026-06-25 13:41:21.593412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f7253b8835f'
down_revision: Union[str, Sequence[str], None] = '0947ef779dea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_table('patients')
    op.drop_table('doctors')
    op.drop_table('hospitals')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('disease', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('doctor_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('hospital_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('is_closed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('report_pdf_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('reports_doctor_id_fkey')),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('reports_hospital_id_fkey')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('reports_patient_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('reports_pkey'))
    )
    op.create_table('hospitals',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('hospital_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('hospital_address', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('hospitals_pkey'))
    )
    op.create_table('patients',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=70), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('phone_no', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('pfp_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gmail', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('patients_pkey'))
    )
    op.create_table('doctors',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=70), autoincrement=False, nullable=False),
    sa.Column('gmail', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('phone_no', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('specialization', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('experience', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qualifications', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('pfp_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('biometric_method', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('verification_code', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('doctor_id', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('pin', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('agreed_pin_warn', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('accepted_terms', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('hospital_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('doctors_hospital_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('doctors_pkey'))
    )
    # ### end Alembic commands ###
