"""Edit column name from report_pdf_url to report_file_name in reports table.

Revision ID: ab6266e02e78
Revises: 5f7253b8835f
Create Date: 2026-07-10 13:23:55.590504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab6266e02e78'
down_revision: Union[str, Sequence[str], None] = '5f7253b8835f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.alter_column('reports', 'report_pdf_url', new_column_name='report_file_name')
    # ### end Alembic commands ###
